In [ ]:
#1.	Create a list of 5 integers. Perform and print the result of the following operations: 
# append, extend, insert, remove, pop, clear, index, count, sort, and reverse

In [1]:
List = [1,2,3,4,5] # created a list of 5 integers
print(List)

[1, 2, 3, 4, 5]


In [2]:
# append : Append is used to add the elements into a list , when append is used the new element is added to the end of the list.

List.append(6)
print(List) 

[1, 2, 3, 4, 5, 6]


In [4]:
# extend : The list.extend() method is used to append all elements of an iterable (like another list) to the end of the current list. 
#It modifies the original list in place and does not return a new list.

List_a = [1,2,3]
List_b = [4,5,6]

List_a.extend(List_b)
print(List_a)

[1, 2, 3, 4, 5, 6]


In [7]:
# insert : the List.insert() methos id used to add new elements at any position, 
# need to provide the index value where the new element need to be inserted

List.insert(3,7)
print(List)

[1, 2, 3, 7, 4, 5, 6]


In [2]:
# remove : it is used to remove a specific value from a list 
# he remove() method deletes only the first occurrence of the value you specify.
List = [26,36,3,56,76]
List.remove(3)
print(List)

[26, 36, 56, 76]


In [6]:
# pop : The pop() method removes the last item in a list, but it lets you work 
# with that item after removing it.
List= [15,20,50,36,70,50,100]
List.pop()
print(List)

[15, 20, 50, 36, 70, 50]


In [8]:
# clear : The clear() method removes all the elements from a list.

List = [1,2,3,4,5,6]
print(List)

List.clear()
print(List)

[1, 2, 3, 4, 5, 6]
[]


In [10]:
# index : To find the position of an element in a Python list, the most common approach is 
#to use the built-in list.index() method, 
#which returns the index of the first occurrence of the specified value.

List = [10,20,25,35,40,60,56,78,96,45,50]
print(List)
print(List.index(45))


[10, 20, 25, 35, 40, 60, 56, 78, 96, 45, 50]
9


In [11]:
# count : The count() method in Python is used to count the number of occurrences of a specified value in a list or string.

List = [10,20,25,35,40,25,60,56,78,96,45,25,50]
print(List)
count_list = List.count(25)
print(count_list)

[10, 20, 25, 35, 40, 25, 60, 56, 78, 96, 45, 25, 50]
3


In [12]:
# sort : The sort() method in Python sorts the elements of a list in ascending order by default. 
#It can also sort values in descending order or based on a custom function.
List = [10,20,25,35,40,25,60,56,78,96,45,25,50]
print(List)

List.sort()
print(List)

[10, 20, 25, 35, 40, 25, 60, 56, 78, 96, 45, 25, 50]
[10, 20, 25, 25, 25, 35, 40, 45, 50, 56, 60, 78, 96]


In [17]:
# reverse :  .reverse() method on the list to reverse it in place. Example: list_name.reverse(). This modifies the original list.

List = [10,20,25,35,40,25,60,56,78,96,45,25,50]
print(List)

List.reverse()
print(List)

# by using sorting
List.sort()
print(List)

List.sort(reverse = True)
print(List)

[10, 20, 25, 35, 40, 25, 60, 56, 78, 96, 45, 25, 50]
[50, 25, 45, 96, 78, 56, 60, 25, 40, 35, 25, 20, 10]
[10, 20, 25, 25, 25, 35, 40, 45, 50, 56, 60, 78, 96]
[96, 78, 60, 56, 50, 45, 40, 35, 25, 25, 25, 20, 10]


In [1]:
# 2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. 
# What happens? Explain why.

# creating a tuple

# A tuple looks just like a list except you use parentheses instead of square brackets

# Student tuple
Student_names = ("Ramesh", "Aryan", "sharukh")

# changing a name in a tuple
Student_names[1] = "Tom Cruise"
print(Student_names)


# this error is because "A Tuple is immutable" once created we cannot change , add or remove elements

TypeError: 'tuple' object does not support item assignment

In [2]:
# 3. Create a set of integers with some duplicate values. Print the set and explain the output.

"""
1. Set in Python is used to store a collection of items
2. No duplicates are allowed
3. mutable we can add or remove elements after the creation
"""

Set = {12,12,50,11,50,12,60,11,60}

print(type(Set))
print(Set)

# since set dont allow duplicate values the output shown as the uniquye valus inserted

<class 'set'>
{50, 11, 12, 60}


In [4]:
"""
4.Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'.
Print the final dictionary.
"""

Employee = {
    'Name' : 'Sharukh',
    'age' : 30,
    'city' : 'Hyderabad'
}

print(Employee)

# adding a new key value

Employee['email'] = "Sharukh@gmail.com"
print(Employee)

# updating the age
print(Employee)
print("before updating the age the age value is " + str(Employee['age'])) # since string and integer cannot concatenate so converting the integer value to string
Employee['age'] = 25
print(Employee)
print("After updating the age the age value is " + str(Employee['age']))


{'Name': 'Sharukh', 'age': 30, 'city': 'Hyderabad'}
{'Name': 'Sharukh', 'age': 30, 'city': 'Hyderabad', 'email': 'Sharukh@gmail.com'}
{'Name': 'Sharukh', 'age': 30, 'city': 'Hyderabad', 'email': 'Sharukh@gmail.com'}
before updating the age the age value is 30
{'Name': 'Sharukh', 'age': 25, 'city': 'Hyderabad', 'email': 'Sharukh@gmail.com'}
After updating the age the age value is 25


In [5]:
"""
5.Write a script that checks if a person is eligible to vote (age ≥ 18). 
Take age as a variable and print the appropriate message.
"""

age = int(input("Enter your age:"))

if age >= 18:
    print("Eligible for voting")
else:
    print("Not Eligible for voting")

    

Enter your age: 18


Eligible for voting


In [6]:
"""
6.	Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'

"""

Marks = int(input("Enter Marks: "))

if Marks >= 90:
    print("Grade : A")
elif Marks >= 75 and Marks <= 89:
    print("Grade : B")
elif Marks >= 50 and Marks <= 74:
    print("Grade : C")
else:
    print("Grade : Fail")
    

Enter Marks:  75


Grade : B


In [8]:
"""
7.	Given a number, check if it's positive, and if it is also even. 
If not positive, print if it's zero or negative.
"""

Number  = int(input("Enter a number: "))

if Number > 0:
    if Number % 2 == 0:
        print("Positive and even")
    else: 
        print("Positive but odd")
elif Number == 0:
    print("Zero")
else:
    print("Negative")

Enter a number:  5


Positive but odd


In [ ]:
#                          Section B

In [9]:
"""
8.	Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10

"""

# importing numpy

import numpy as np

#scalar
Scalar = np.array(5)
print("Scalar :", Scalar)

#Creating a 1D array with values 1 to 5
Array_1D = np.array([1,2,3,4,5])
print("Array_1D :", Array_1D)

#Creating a 2D array with values from 10 to 60 in 10 steps
Array_2D = np.array([[10,20,30],[40,50,60]])
print("Array_2D :\n", Array_2D)

Scalar : 5
Array_1D : [1 2 3 4 5]
Array_2D :
 [[10 20 30]
 [40 50 60]]


In [10]:
"""
9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().
"""

import numpy as np

Array_4D = np.random.randint(0,101,size =(4,4)) # to include 100 I have used 101
print(Array_4D)

[[34 11 65 36]
 [ 5 40 47 89]
 [ 2 44 48  8]
 [35 60 60 50]]


In [11]:
"""
10.	Create a 2D numpy array of shape (3x3). 
Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.
"""

import numpy as np
import pandas as pd

Array_3D = np.random.randint(0,51,size = (3,3))
print(Array_3D)

df = pd.DataFrame(Array_3D, columns = ['A', 'B','C'])
print(df)

[[25 45 34]
 [29 20 12]
 [30 30 48]]
    A   B   C
0  25  45  34
1  29  20  12
2  30  30  48


In [ ]:
#                                Section - C

In [2]:
"""
11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows

"""
import pandas as pd
import numpy as np

# creating dataframe manually

data = {
    'Name': ['Ravi', 'Anjali', 'Kiran', 'Sneha', 'Amit', 
             'Ravi', 'Pooja', 'Vikram', 'Neha', 'Kiran'],
    'Age': [25, 30, 28, 22, 35, 25, 27, 31, 29, 28],
    'City': ['Hyderabad', 'Mumbai', 'Delhi', 'Chennai', 'Pune',
             'Hyderabad', 'Bangalore', 'Delhi', 'Mumbai', 'Delhi'],
    'Salary': [50000, 60000, np.nan, 45000, 70000,
               50000, 52000, np.nan, 61000, np.nan]
}

df = pd.DataFrame(data)

print("Original DataFrame")
print(df)


Original DataFrame
     Name  Age       City   Salary
0    Ravi   25  Hyderabad  50000.0
1  Anjali   30     Mumbai  60000.0
2   Kiran   28      Delhi      NaN
3   Sneha   22    Chennai  45000.0
4    Amit   35       Pune  70000.0
5    Ravi   25  Hyderabad  50000.0
6   Pooja   27  Bangalore  52000.0
7  Vikram   31      Delhi      NaN
8    Neha   29     Mumbai  61000.0
9   Kiran   28      Delhi      NaN


In [3]:
# info()
print("\nInfo:")
print(df.info())



Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  7 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes
None


In [4]:
# describe()
print("\ndescribe")
print(df.describe())


describe
             Age        Salary
count  10.000000      7.000000
mean   28.000000  55428.571429
std     3.620927   8599.557021
min    22.000000  45000.000000
25%    25.500000  50000.000000
50%    28.000000  52000.000000
75%    29.750000  60500.000000
max    35.000000  70000.000000


In [6]:
#select name and city columns
print("\nselecting name and city")
print(df[['Name','City']])


selecting name and city
     Name       City
0    Ravi  Hyderabad
1  Anjali     Mumbai
2   Kiran      Delhi
3   Sneha    Chennai
4    Amit       Pune
5    Ravi  Hyderabad
6   Pooja  Bangalore
7  Vikram      Delhi
8    Neha     Mumbai
9   Kiran      Delhi


In [7]:
# Drop 'City' column

df = df.drop('City', axis = 1)
print("\nAfter dropping the city column")
print(df)


After dropping the city column
     Name  Age   Salary
0    Ravi   25  50000.0
1  Anjali   30  60000.0
2   Kiran   28      NaN
3   Sneha   22  45000.0
4    Amit   35  70000.0
5    Ravi   25  50000.0
6   Pooja   27  52000.0
7  Vikram   31      NaN
8    Neha   29  61000.0
9   Kiran   28      NaN


In [8]:

#  Fill any missing values in 'Salary' column with the mean

mean_salary = df['Salary'].mean()
df['Salary'] = df['Salary'].fillna(mean_salary)

print(df)

     Name  Age        Salary
0    Ravi   25  50000.000000
1  Anjali   30  60000.000000
2   Kiran   28  55428.571429
3   Sneha   22  45000.000000
4    Amit   35  70000.000000
5    Ravi   25  50000.000000
6   Pooja   27  52000.000000
7  Vikram   31  55428.571429
8    Neha   29  61000.000000
9   Kiran   28  55428.571429


In [9]:
# Remove any duplicate rows

df = df.drop_duplicates()
print(df)

     Name  Age        Salary
0    Ravi   25  50000.000000
1  Anjali   30  60000.000000
2   Kiran   28  55428.571429
3   Sneha   22  45000.000000
4    Amit   35  70000.000000
6   Pooja   27  52000.000000
7  Vikram   31  55428.571429
8    Neha   29  61000.000000
